/* Generated by Iode v0.0.1 */

function Greeter(name, age) {
  this.name = name;
  this.age = age;
  this.name = "John";
  this.hello = function() {
    console.log("Cool! Hey " + name + "! You're " + age + "!");
  };
};