/* Generated by Iode v0.0.1 */

function hello(name, age) {
  if (age == null || age == undefined) {
    age = 99;
  }
  console.log("My name is " + name + "! I'm " + age + " years old!");
};

hello("John", null);
