/* Generated by Iode v0.0.1 */

{
  "name": "iode",
  "description": "A fast, empirical, useful programming language.",
  "version": "0.0.1",
  "author": "Danilo Lekovic <danilo@lekovic.ca>",
  "license": "MIT",
  "preferGlobal": true,
  "dependencies":
}
}