/* Generated by Iode v0.0.1 */

function greet(name) {
  if (!(typeof(name) === "string")) {
    throw 'Expected type of "string" for var "name"';
  }
  console.log("Hey " + name + "!");
};

greet("John");