// For use with HTML files
var elements = document.getElementsByTagName("script");

function httpGet(address) {
  var xhr = new XMLHttpRequest();
  xhr.open('GET', address, false);
  xhr.send(null);
  if (xhr.status === 200) {
    return xhr.responseText;
  }
}

function generate(code) {
  var parser = new Parser(code.toString(), null);
  var ast = parser.parse();
  var outputCode = '/* Generated by Iode v0.0.1 */\n';

  try {
    for (var expr in ast) {
      outputCode += '\n' + ast[expr].val;
    }
  } catch (e) {
    console.log('[x] Could not generate code. ' + e);
  }
}

for (var i = 0; i < elements.length; i++) {
    if (elements[i].type == "text/iode") {
      var previousCode = elements[i].innerHTML;
      var src = "";
      if (elements[i].hasAttribute("src")) {
        src += httpGet(elements[i].src);
        eval(generate(src + previousCode));
        elements[i].innerHTML = "/* Compiled by Iode v0.0.1 */\n" + generate(src + previousCode);
        elements[i].type = "text/javascript";
      }
}
